Restore but fix test for read perms of PID file in init script.

diff --git a/install/percona-agent b/install/percona-agent
--- a/install/percona-agent
+++ b/install/percona-agent
@@ -115,6 +115,10 @@ _seq() {
 
 getpid() {
    if [ -f $PIDFILE ]; then
+      if [ ! -r $PIDFILE ]; then
+         echo "Cannot read $PIDFILE." >&2
+         exit 1
+      fi
       pid=`cat $PIDFILE`
       # Verify that a process with this pid is still running.
       pid=`$PSEXE -p $pid | grep $pid | grep -v grep | tail -1 | awk '{print $1}'`
