Makes init script more understandable by refactoring to use functions

diff --git a/install/percona-agent b/install/percona-agent
--- a/install/percona-agent
+++ b/install/percona-agent
@@ -49,7 +49,7 @@ LOGFILE="$BASEDIR/$SERVICE.log"
 
 # Agent does not manager its own PID file; system is expected to manager this.
 PIDFILE="$BASEDIR/$SERVICE.pid"
-pid=""
+PID=""
 
 # Allow configuration overrides in /etc/sysconfig/$SERVICE
 CONFIGFILE="/etc/sysconfig/$SERVICE"
@@ -113,42 +113,57 @@ _seq() {
    awk "BEGIN { for(i=1; i<=$i; i++) print i; }"
 }
 
-testpid() {
-	# This function will check if the process under $pid runs $SERVICE
-    # if not, it will delete $PIDFILE and set $pid to empty string
-    psoutput=`ps -p "$pid" -o pid,comm | grep -w "$pid"` 
-    pid=`echo "$psoutput" | awk '{print $1}'`
-    # Make sure $SERVICE shows up in command name
-    match=`echo "$psoutput" | awk '{print $2}' | grep "$SERVICE"`
+is_pid_running_agent() {
+	# This will check if the process under $PID runs $SERVICE
+    if [ -z "$PID" ]; then
+        # ps does not like empty string as pid
+        return 1
+    fi
+    match=`ps -p "$PID" -o comm | grep -o "$SERVICE"`
     if [ -z "$match" ]; then
-       pid=""
-       # This is a stale pid file.
-       rm -f "$PIDFILE"
-       # Check if message to display was provided
-       if [ ! -z "$1" ]; then
-          echo "$1"
-       fi
+       return 1
+    fi
+    return 0
+}
+
+remove_stale_pidfile() {
+    # Remove the pidfile checking the success of operation
+    # if succeeds echo optional $1 parameter
+    # Note: rm will always exit with status 0
+    found="no"
+    if [ -f "$PIDFILE" ]; then
+        found="yes"
+    fi
+    rm -f "$PIDFILE"
+    if [ $found = "yes" ] && [ ! -f "$PIDFILE" ] && [ -n "$1" ]; then
+        # If file was actually deleted and a message to display was provided
+        echo "$1"
     fi
 }
 
-getpid() {
-   if [ -f $PIDFILE ]; then
-      if [ ! -r $PIDFILE ]; then
-         echo "Cannot read $PIDFILE." >&2
-         exit 1
-      fi
-      pid=`cat $PIDFILE`
-	  # Verify that a process with this pid is still running percona-agent
-      testpid "Removed stale pid file: $PIDFILE"
+get_pid_from_file() {
+   PID=""
+   if [ ! -f $PIDFILE ]; then
+      return 1
    fi
+
+   if [ ! -r $PIDFILE ]; then
+      echo "Cannot read $PIDFILE." >&2
+      exit 1
+   fi
+
+   PID=`cat $PIDFILE`
+   return 0
 }
 
 start() {
    chown "$USERNAME" "$BASEDIR" || exit 1
 
    echo "Starting $SERVICE..."
-   getpid
-   if [ "$pid" ]; then
+   get_pid_from_file
+   if ! is_pid_running_agent; then
+        remove_stale_pidfile "Removed stale pid file: $PIDFILE"
+   else
       echo "$SERVICE is already running."
       exit 0
    fi
@@ -160,8 +175,7 @@ start() {
    # so let's give an agent some time to start
    echo "Waiting for $SERVICE to start..."
    for x in $(_seq $START_TIMEOUT); do
-       getpid
-       if [ -n "$pid" ]; then
+       if get_pid_from_file && is_pid_running_agent; then
            break
        fi
        sleep 1
@@ -169,7 +183,7 @@ start() {
 
    # Process is started in background so $? does not have its exit status.
    # Instead, check that it's running by trying to get its PID.
-   if [ -z "$pid" ]; then
+   if ! is_pid_running_agent; then
       echo "Fail.  Check $LOGFILE for details."
       exit 1
    else
@@ -179,43 +193,43 @@ start() {
 
 stop() {
     echo "Stopping $SERVICE..."
-    getpid
-    if [ "X$pid" = "X" ]; then
+    get_pid_from_file
+    if ! is_pid_running_agent; then
+        remove_stale_pidfile "Removed stale pid file: $PIDFILE"
+    fi
+    if ! is_pid_running_agent; then
         echo "$SERVICE is not running."
         return 0
     else
-         # Running so try to stop it.
-        kill $pid >/dev/null 2>&1
+        # Running so try to stop it.
+        kill "$PID" >/dev/null 2>&1
         if [ $? -ne 0 ]; then
-            # An explanation for the failure should have been given
             echo "Unable to stop $SERVICE."
             return 1
         fi
  
         #  Loop until it does.
         echo "Waiting for $SERVICE to exit..."
-        savepid=$pid
+        savepid=$PID
         for x in $(_seq $STOP_TIMEOUT); do
-            testpid
-            if [ -z "$pid" ]; then
-                break
+            if ! is_pid_running_agent; then
+                break;    
             fi
             sleep 1
         done
  
-        pid=$savepid
-        testpid
-        if [ "X$pid" != "X" ]; then
-            echo "Time out waiting for $SERVICE to exit.  Trying kill -9 $pid..."
-            kill -9 $pid
+        PID=$savepid
+        if is_pid_running_agent; then
+            echo "Time out waiting for $SERVICE to exit.  Trying kill -9 $PID..."
+            kill -9 $PID
         fi
  
-        pid=$savepid
-        testpid
-        if [ "X$pid" != "X" ]; then
+        PID=$savepid
+        if is_pid_running_agent; then
             echo "Failed to stop $SERVICE."
             return 1
         else
+            remove_stale_pidfile 
             echo "Stopped $SERVICE."
             return 0
         fi
@@ -223,9 +237,8 @@ stop() {
 }
  
 status() {
-   getpid
-   if [ "$pid" ]; then
-      echo "$SERVICE is running ($pid)."
+   if get_pid_from_file && is_pid_running_agent; then
+      echo "$SERVICE is running ($PID)."
       exit 0
    else
       echo "$SERVICE is not running."
